name: Build and deploy docusaurus site to AWS
on:     
  push:
    branches:
      - main
jobs:
  run:
    name: Build and Deploy to s3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
                
        - name: Install dependencies
          run: npm ci
          working-directory: /
          
        - name: Build
          run: npm run build
          working-directory: /

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: /build
            bucket: ${{ secrets.DEVSITE_S3_BUCKET }}
            bucket-region: ${{ secrets.DEVSITE_S3_BUCKET_REGION }}
            dist-id: ${{ secrets.DEVSITE_CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
